name: Commented Pull Request
run-name: Verify /verify comment (#${{ github.event.issue.number }})

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pullRequestHandler:
    name: Verify comment (/verify)
    runs-on: windows-latest
    steps:

      - name: Checkout bucket
        uses: actions/checkout@v7

      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@v3.0.0
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOOP_BRANCH: develop
